### ISSUE TITLE
libres master does not compile on ubuntu 18.04

### ISSUE THREAD

**Issue by geirev** [equinor/libres#510]
[ 16%] Building CXX object lib/CMakeFiles/res.dir/enkf/ert_test_context.cpp.o
/home/geve/ERT/libres/lib/enkf/ert_test_context.cpp: In function ‘ert_test_context_type* ert_test_context_alloc(const char*, const char*)’:
/home/geve/ERT/libres/lib/enkf/ert_test_context.cpp:70:3: error: ‘test_work_area_set_store’ was not declared in this scope
   test_work_area_set_store( work_area , false );
   ^~~~~~~~~~~~~~~~~~~~~~~~
/home/geve/ERT/libres/lib/enkf/ert_test_context.cpp:70:3: note: suggested alternative: ‘test_work_area_get_cwd’
   test_work_area_set_store( work_area , false );
   ^~~~~~~~~~~~~~~~~~~~~~~~
   test_work_area_get_cwd
/home/geve/ERT/libres/lib/enkf/ert_test_context.cpp: In function ‘void ert_test_context_set_store(ert_test_context_type*, bool)’:
/home/geve/ERT/libres/lib/enkf/ert_test_context.cpp:184:3: error: ‘test_work_area_set_store’ was not declared in this scope
   test_work_area_set_store( test_context->work_area , store );
   ^~~~~~~~~~~~~~~~~~~~~~~~
/home/geve/ERT/libres/lib/enkf/ert_test_context.cpp:184:3: note: suggested alternative: ‘test_work_area_get_cwd’
   test_work_area_set_store( test_context->work_area , store );
   ^~~~~~~~~~~~~~~~~~~~~~~~
   test_work_area_get_cwd
lib/CMakeFiles/res.dir/build.make:3350: recipe for target 'lib/CMakeFiles/res.dir/enkf/ert_test_context.cpp.o' failed
make[2]: *** [lib/CMakeFiles/res.dir/enkf/ert_test_context.cpp.o] Error 1
CMakeFiles/Makefile2:3749: recipe for target 'lib/CMakeFiles/res.dir/all' failed
make[1]: *** [lib/CMakeFiles/res.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by joakim-hove** [comment]
This is because of this change in libecl: https://github.com/equinor/libecl/pull/562 - the followup PR in libres: https://github.com/equinor/libres/pull/507 has not been merged yet; so right now the master version libres + libecl is broken for everyone.

Until the libres PR is merged you must compile with a slightly older libecl release; i.f you look at the file `.libecl_version` in the root of the libres distribution you will see the libecl version which is used on travis when building libres - that is currently `2.4.b1`.

**Comment by ManInFez** [comment]
Can this be closed?

**Comment by geirev** [comment]
Yes, this was resolved with the PR in libres: #507
